import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiShadcnui,
  SiRedux,
  SiGsap,
  SiHtml5,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiFastify,
  SiFastapi,
  SiPython,
  SiGo,
  SiBun,
  SiDjango,
  SiTrpc,
  SiPostgresql,
  SiMongodb,
  SiPrisma,
  SiDrizzle,
  SiRedis,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiApachecassandra,
  SiClickhouse,
  SiDocker,
  SiGithubactions,
  SiCloudflare,
  SiVercel,
  SiKubernetes,
  SiTerraform,
  SiLinux,
  SiNginx,
  SiGrafana,
  SiWebrtc,
  SiApachekafka,
  SiRabbitmq,
  SiSocketdotio,
  SiMqtt,
  SiPusher,
  SiGraphql,
  SiStripe,
  SiApollographql,
  SiAuth0,
  SiJest,
  SiCypress,
  SiVitest,
  SiJsonwebtokens,
  SiOwasp,
  SiSnyk,
  SiGit,
  SiTurborepo,
  SiNx,
  SiVite,
  SiEslint,
  SiPrettier,
  SiWebpack,
  SiPostman,
} from "react-icons/si";
import {
  FaAws,
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaLinkedin,
  FaTelegram,
  FaWhatsapp,
} from "react-icons/fa";
import {
  LuCable,
  LuZap,
  LuLayers,
  LuNetwork,
  LuBrainCircuit,
  LuLayoutGrid,
  LuMail,
  LuShieldCheck,
  LuLayers3,
  LuInfinity,
  LuBoxes,
  LuFlame,
  LuPhoneCall,
} from "react-icons/lu";
import { Mail } from "lucide-react";
import { FaXTwitter } from "react-icons/fa6";

export const SKILLS = [
  {
    category: "Frontend",
    skills: [
      { name: "React", icon: SiReact, color: "#61dafb" },
      { name: "Next.js", icon: SiNextdotjs, color: "#ffffff" },
      { name: "TypeScript", icon: SiTypescript, color: "#3178c6" },
      { name: "Tailwind CSS", icon: SiTailwindcss, color: "#38bdf8" },
      { name: "ShadcnUi", icon: SiShadcnui, color: "#ffffff" },
      { name: "Zustand", icon: LuBoxes, color: "#443e38" },
      { name: "Redux Toolkit", icon: SiRedux, color: "#764abc" },
      { name: "Framer Motion", icon: LuFlame, color: "#ea4aaa" },
      { name: "GSAP", icon: SiGsap, color: "#88ce02" },
      { name: "HTML5 & CSS3", icon: SiHtml5, color: "#e34f26" },
    ],
  },
  {
    category: "Backend",
    skills: [
      { name: "Node.js", icon: SiNodedotjs, color: "#5fa04e" },
      { name: "Express.js", icon: SiExpress, color: "#ffffff" },
      { name: "NestJS", icon: SiNestjs, color: "#e0234e" },
      { name: "Fastify", icon: SiFastify, color: "#ffffff" },
      { name: "FastApi", icon: SiFastapi, color: "#009688" },
      { name: "Python", icon: SiPython, color: "#3776ab" },
      { name: "GoLang", icon: SiGo, color: "#00add8" },
      { name: "Bun", icon: SiBun, color: "#fbf0df" },
      { name: "Django", icon: SiDjango, color: "#092e20" },
      { name: "tRPC", icon: SiTrpc, color: "#398ccb" },
    ],
  },
  {
    category: "Databases & ORM",
    skills: [
      { name: "PostgreSQL", icon: SiPostgresql, color: "#4169e1" },
      { name: "MongoDB", icon: SiMongodb, color: "#00ed64" },
      { name: "Prisma", icon: SiPrisma, color: "#5a67d8" },
      { name: "Drizzle", icon: SiDrizzle, color: "#c5f74f" },
      { name: "Redis", icon: SiRedis, color: "#dc382d" },
      { name: "MySQL", icon: SiMysql, color: "#4479a1" },
      { name: "Supabase", icon: SiSupabase, color: "#3ecf8e" },
      { name: "Firebase", icon: SiFirebase, color: "#ffca28" },
      { name: "Cassandra", icon: SiApachecassandra, color: "#1287b1" },
      { name: "ClickHouse", icon: SiClickhouse, color: "#ffcc00" },
    ],
  },
  {
    category: "Cloud & DevOps",
    skills: [
      { name: "AWS", icon: FaAws, color: "#ff9900" },
      { name: "Docker", icon: SiDocker, color: "#2496ed" },
      { name: "GitHub Actions", icon: SiGithubactions, color: "#2088ff" },
      { name: "Cloudflare", icon: SiCloudflare, color: "#f38020" },
      { name: "Vercel", icon: SiVercel, color: "#ffffff" },
      { name: "Kubernetes", icon: SiKubernetes, color: "#326ce5" },
      { name: "Terraform", icon: SiTerraform, color: "#7b42bc" },
      { name: "Linux / Bash", icon: SiLinux, color: "#f57c00" },
      { name: "Nginx", icon: SiNginx, color: "#009639" },
      { name: "Grafana", icon: SiGrafana, color: "#f47a1f" },
    ],
  },
  {
    category: "Real-time & Messaging",
    skills: [
      { name: "WebSockets", icon: LuCable, color: "#ffffff" },
      { name: "WebRTC", icon: SiWebrtc, color: "#ffffff" },
      { name: "gRPC", icon: LuZap, color: "#34d399" },
      { name: "Kafka", icon: SiApachekafka, color: "#ffffff" },
      { name: "BullMQ", icon: LuLayers, color: "#ff4757" },
      { name: "RabbitMQ", icon: SiRabbitmq, color: "#ff6600" },
      { name: "Socket.io", icon: SiSocketdotio, color: "#010101" },
      { name: "MQTT", icon: SiMqtt, color: "#660066" },
      { name: "Pusher", icon: SiPusher, color: "#3075b4" },
      { name: "Amazon SQS", icon: LuInfinity, color: "#ff4f8b" },
    ],
  },
  {
    category: "APIs & Integrations",
    skills: [
      { name: "GraphQL", icon: SiGraphql, color: "#e10098" },
      { name: "REST APIs", icon: LuNetwork, color: "#38bdf8" },
      { name: "Stripe", icon: SiStripe, color: "#635bff" },
      { name: "AI Integrations", icon: LuBrainCircuit, color: "#8a2be2" },
      { name: "Microservices", icon: LuLayoutGrid, color: "#94a3b8" },
      { name: "Apollo GraphQL", icon: SiApollographql, color: "#311c87" },
      { name: "Twilio", icon: LuPhoneCall, color: "#f22f46" },
      { name: "SendGrid", icon: LuMail, color: "#00bfff" },
      { name: "Resend", icon: LuMail, color: "#ffffff" },
      { name: "Auth0", icon: SiAuth0, color: "#eb5424" },
    ],
  },
  {
    category: "Testing & Security",
    skills: [
      { name: "Jest", icon: SiJest, color: "#c21325" },
      { name: "Cypress", icon: SiCypress, color: "#17202c" },
      { name: "Playwright", icon: LuShieldCheck, color: "#2ead33" },
      { name: "Vitest", icon: SiVitest, color: "#fcc72b" },
      { name: "JSON Web Tokens", icon: SiJsonwebtokens, color: "#ffffff" },
      { name: "Helmet", icon: LuShieldCheck, color: "#f2f3f4" },
      { name: "SonarQube", icon: LuLayers3, color: "#4e9bcd" },
      { name: "OWASP Top 10", icon: SiOwasp, color: "#ffffff" },
      { name: "Snyk", icon: SiSnyk, color: "#4c1e7d" },
      { name: "Supertest", icon: LuShieldCheck, color: "#34d399" },
    ],
  },
  {
    category: "Tools & Architecture",
    skills: [
      { name: "Git", icon: SiGit, color: "#f05032" },
      { name: "Turborepo", icon: SiTurborepo, color: "#ef4444" },
      { name: "Nx Monorepo", icon: SiNx, color: "#143157" },
      { name: "Vite", icon: SiVite, color: "#646cff" },
      { name: "ESLint", icon: SiEslint, color: "#4b32c3" },
      { name: "Prettier", icon: SiPrettier, color: "#f7b93e" },
      { name: "Webpack", icon: SiWebpack, color: "#8ed6fb" },
      { name: "Postman", icon: SiPostman, color: "#ff6c37" },
      { name: "Docker Compose", icon: SiDocker, color: "#2496ed" },
      { name: "DDD / Clean Arch", icon: LuLayers3, color: "#a855f7" },
    ],
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "Full-stack e-commerce solution with real-time inventory management, payment processing, and advanced analytics.",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "AWS"],
    image: "/project-ecommerce.png",
    github: "#",
    live: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Real-time Collaboration Tool",
    description:
      "Web-based collaboration platform with WebSockets for real-time data synchronization and document editing.",
    technologies: ["React", "Node.js", "WebSockets", "MongoDB", "Redis"],
    image: "/project-collaboration.png",
    github: "#",
    live: "#",
    featured: true,
  },
  {
    id: 3,
    title: "Microservices Architecture",
    description:
      "Scalable microservices system using Node.js, Docker, Kubernetes, and event-driven architecture with Kafka.",
    technologies: ["Node.js", "Docker", "Kubernetes", "Kafka", "PostgreSQL"],
    image: "/project-microservices.png",
    github: "#",
    live: "#",
    featured: true,
  },
  {
    id: 4,
    title: "AI Chat Application",
    description:
      "Intelligent chat application with NLP, persistent storage, and user authentication system.",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Prisma", "TypeScript"],
    image: "/project-ai-chat.png",
    github: "#",
    live: "#",
  },
  {
    id: 5,
    title: "Video Streaming Platform",
    description:
      "Video streaming service with HLS, real-time transcoding, and AWS S3 integration.",
    technologies: ["React", "Node.js", "AWS", "Docker", "PostgreSQL"],
    image: "/project-video-streaming.png",
    github: "#",
    live: "#",
  },
  {
    id: 6,
    title: "Analytics Dashboard",
    description:
      "Real-time analytics dashboard with data visualization, filtering, and export capabilities.",
    technologies: ["Next.js", "React", "PostgreSQL", "Tailwind CSS", "Node.js"],
    image: "/project-analytics.png",
    github: "#",
    live: "#",
  },
];

export const SOCIAL_LINKS = [
  { name: "Email", icon: Mail, href: "mailto:shahmdmahi24@gmail.com" },
  {
    name: "LinkedIn",
    icon: FaLinkedin,
    href: "https://www.linkedin.com/in/shah-md-mahi",
  },
  { name: "GitHub", icon: FaGithub, href: "https://github.com/ShahMdMahi" },
  {
    name: "Facebook",
    icon: FaFacebook,
    href: "https://facebook.com/Shah.Md.Mahi13",
  },
  {
    name: "Telegram",
    icon: FaTelegram,
    href: "https://t.me/ShahMdMahi",
  },
  {
    name: "Whatsapp",
    icon: FaWhatsapp,
    href: "https://wa.me/+8801712345678",
  },
  {
    name: "Discord",
    icon: FaDiscord,
    href: "https://discord.com/users/803554071856283649",
  },
  {
    name: "X",
    icon: FaXTwitter,
    href: "https://twitter.com/Shah_Md_Mahi",
  },
];

export const NAVIGATION = [
  { name: "Home", href: "#home" },
  { name: "Skills", href: "#skills" },
  { name: "Projects", href: "#projects" },
  { name: "About", href: "#about" },
  { name: "Contact", href: "#contact" },
];
